#!/usr/bin/env python3
"""Write ~/.secrets-env.staging.ps1 for Windows agent workstations.

One-time (or re-run after key rotation). Reads ~/.aws/*.txt plus
prod/ec2-secrets from AWS Secrets Manager. Never commit the output file.

Usage:
  python scripts/bootstrap-windows-secrets.py
  . ~/.secrets-env.staging.ps1
"""

from __future__ import annotations

import json
from pathlib import Path

import boto3

HOME = Path.home()
AWS = HOME / ".aws"
OUTPUT = HOME / ".secrets-env.staging.ps1"


def read_txt(name: str) -> str:
    path = AWS / name
    return path.read_text(encoding="utf-8").strip() if path.exists() else ""


def main() -> None:
    sec = json.loads(
        boto3.client("secretsmanager", region_name="us-east-1").get_secret_value(
            SecretId="prod/ec2-secrets"
        )["SecretString"]
    )

    # Prefer the petralabx fine-grained PAT for org automation (portal + skills
    # + PLX_MC). Keep a separate export so callers can opt in without clobbering
    # a machine-local Secret_Github.txt used for personal taylorvalton work.
    petra = (
        sec.get("PETRALABX_GITHUB_TOKEN")
        or sec.get("PETRALABX_GITHUB")
        or ""
    )
    values = {
        "PETRALABX_GITHUB_TOKEN": petra,
        "GITHUB_TOKEN": read_txt("Secret_Github.txt")
        or petra
        or sec.get("GITHUB_TOKEN", ""),
        "MICROSOFT_GRAPH_TENANT_ID": read_txt("PLX_FORMS_DIRECTORY_TENANT_ID.txt")
        or sec.get("MICROSOFT_GRAPH_TENANT_ID", ""),
        "MICROSOFT_GRAPH_CLIENT_ID": read_txt("PLX_FORMS_APPICATION_ID.txt")
        or sec.get("MICROSOFT_GRAPH_CLIENT_ID", ""),
        "MICROSOFT_GRAPH_CLIENT_SECRET": read_txt("forms-api-secret-value.txt")
        or sec.get("MICROSOFT_GRAPH_CLIENT_SECRET", ""),
        "MC_MCP_API_KEY": sec.get("PLX_MC_MCP_API_KEY", ""),
        "MC_OPERATOR_EMAIL": "cos@petrasoap.com",
        "PLX_MC_MCP_ENABLED": "1",
        "SWARM_API_KEY": sec.get("SWARM_API_KEY", ""),
    }

    lines = [
        "# Machine-local secrets loader for PLX agent workstations",
        "# Generated by scripts/bootstrap-windows-secrets.py — do not commit",
        "",
        "function Read-SecretFile([string]$Name) {",
        '  $p = Join-Path $HOME ".aws/$Name"',
        "  if (Test-Path $p) { return (Get-Content $p -Raw).Trim() }",
        '  return ""',
        "}",
        "",
    ]

    for key, val in values.items():
        if not val:
            continue
        esc = val.replace("'", "''")
        lines.append(f"$env:{key} = '{esc}'")

    lines.extend(
        [
            "$env:AZURE_TENANT_ID = $env:MICROSOFT_GRAPH_TENANT_ID",
            "$env:AZURE_CLIENT_ID = $env:MICROSOFT_GRAPH_CLIENT_ID",
            "$env:AZURE_CLIENT_SECRET = $env:MICROSOFT_GRAPH_CLIENT_SECRET",
            "",
        ]
    )

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT}")
    print("keys loaded:", ", ".join(k for k, v in values.items() if v))


if __name__ == "__main__":
    main()
