#!/usr/bin/env python3
"""Write workstation secret env files from AWS Secrets Manager + local overrides.

Outputs (never commit):
  ~/.secrets-env.staging.ps1   — full PLX agent workstation hydrate (Windows)
  ~/.secrets-env.github.ps1    — GitHub org PAT only (Windows; safe to profile-source)
  ~/.secrets-env.github        — same for bash/zsh (Linux/macOS/DGX)

Usage:
  python scripts/bootstrap-windows-secrets.py
  . ~/.secrets-env.staging.ps1          # full session
  . ~/.secrets-env.github.ps1           # GitHub org PAT only (Windows)
  source ~/.secrets-env.github          # GitHub org PAT only (Unix)

See docs/runbooks/petralabx-github-token-workstation.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import boto3

HOME = Path.home()
AWS = HOME / ".aws"
OUTPUT_STAGING = HOME / ".secrets-env.staging.ps1"
OUTPUT_GITHUB_PS1 = HOME / ".secrets-env.github.ps1"
OUTPUT_GITHUB_SH = HOME / ".secrets-env.github"


def read_txt(name: str) -> str:
    path = AWS / name
    return path.read_text(encoding="utf-8").strip() if path.exists() else ""


def sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def main() -> None:
    sec = json.loads(
        boto3.client("secretsmanager", region_name="us-east-1").get_secret_value(
            SecretId="prod/ec2-secrets"
        )["SecretString"]
    )

    # Prefer the petralabx fine-grained PAT for org automation (portal + skills
    # + PLX_MC). Secret_Github.txt may already hold the org PAT after rotation.
    petra = sec.get("PETRALABX_GITHUB_TOKEN") or sec.get("PETRALABX_GITHUB") or ""
    github = read_txt("Secret_Github.txt") or petra or sec.get("GITHUB_TOKEN", "")

    values = {
        "PETRALABX_GITHUB_TOKEN": petra or github,
        "GITHUB_TOKEN": github,
        "MICROSOFT_GRAPH_TENANT_ID": read_txt("PLX_FORMS_DIRECTORY_TENANT_ID.txt")
        or sec.get("MICROSOFT_GRAPH_TENANT_ID", ""),
        "MICROSOFT_GRAPH_CLIENT_ID": read_txt("PLX_FORMS_APPICATION_ID.txt")
        or sec.get("MICROSOFT_GRAPH_CLIENT_ID", ""),
        "MICROSOFT_GRAPH_CLIENT_SECRET": read_txt("forms-api-secret-value.txt")
        or sec.get("MICROSOFT_GRAPH_CLIENT_SECRET", ""),
        "MC_MCP_API_KEY": sec.get("PLX_MC_MCP_API_KEY", ""),
        "MC_OPERATOR_EMAIL": "cos@petrasoap.com",
        "PLX_MC_MCP_ENABLED": "1",
        "SWARM_API_KEY": sec.get("SWARM_API_KEY", ""),
    }

    lines = [
        "# Machine-local secrets loader for PLX agent workstations",
        "# Generated by scripts/bootstrap-windows-secrets.py — do not commit",
        "",
        "function Read-SecretFile([string]$Name) {",
        '  $p = Join-Path $HOME ".aws/$Name"',
        "  if (Test-Path $p) { return (Get-Content $p -Raw).Trim() }",
        '  return ""',
        "}",
        "",
    ]

    for key, val in values.items():
        if not val:
            continue
        esc = val.replace("'", "''")
        lines.append(f"$env:{key} = '{esc}'")

    lines.extend(
        [
            "$env:AZURE_TENANT_ID = $env:MICROSOFT_GRAPH_TENANT_ID",
            "$env:AZURE_CLIENT_ID = $env:MICROSOFT_GRAPH_CLIENT_ID",
            "$env:AZURE_CLIENT_SECRET = $env:MICROSOFT_GRAPH_CLIENT_SECRET",
            "",
            "# Also keep a GitHub-only fragment for profile auto-source:",
            "#   . $HOME\\.secrets-env.github.ps1",
            "",
        ]
    )

    OUTPUT_STAGING.write_text("\n".join(lines), encoding="utf-8")

    # GitHub-only fragment (Windows + Unix) for shell-profile auto-source.
    gh_token = values.get("PETRALABX_GITHUB_TOKEN") or values.get("GITHUB_TOKEN") or ""
    if gh_token:
        esc = gh_token.replace("'", "''")
        OUTPUT_GITHUB_PS1.write_text(
            "\n".join(
                [
                    "# GitHub org PAT for petralabx agent work — do not commit",
                    "# Generated by scripts/bootstrap-windows-secrets.py",
                    f"$env:PETRALABX_GITHUB_TOKEN = '{esc}'",
                    f"$env:GITHUB_TOKEN = '{esc}'",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        OUTPUT_GITHUB_SH.write_text(
            "\n".join(
                [
                    "# GitHub org PAT for petralabx agent work — do not commit",
                    "# Generated by scripts/bootstrap-windows-secrets.py",
                    f"export PETRALABX_GITHUB_TOKEN={sh_quote(gh_token)}",
                    f"export GITHUB_TOKEN={sh_quote(gh_token)}",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        try:
            OUTPUT_GITHUB_SH.chmod(0o600)
        except OSError:
            pass

    print(f"wrote {OUTPUT_STAGING}")
    if gh_token:
        print(f"wrote {OUTPUT_GITHUB_PS1}")
        print(f"wrote {OUTPUT_GITHUB_SH}")
    print("keys loaded:", ", ".join(k for k, v in values.items() if v))
    print(
        "tip: profile-source GitHub PAT with "
        "`. $HOME\\.secrets-env.github.ps1` (Windows) or "
        "`source ~/.secrets-env.github` (Unix) — see "
        "docs/runbooks/petralabx-github-token-workstation.md"
    )


if __name__ == "__main__":
    main()
