#!/usr/bin/env python3
"""Generate derived governance surfaces from config/governance-contract.yaml.

The contract YAML is the single source of truth. This script renders it into:
  - a governance block between marker comments in each `surfaces.marker_files`
    entry (e.g. AGENTS.md, CLAUDE.md)
  - a full rewrite of `surfaces.rule_file` (.cursor/rules/governance.mdc)

Usage:
    python scripts/generate-governance-surfaces.py          # write surfaces
    python scripts/generate-governance-surfaces.py --check  # drift gate, exit 1 on drift

Run the write mode after every contract edit. Run --check in pre-commit and CI
so no surface can silently drift from the contract.

Requires: pyyaml
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "config" / "governance-contract.yaml"

START_MARKER = "<!-- governance:auto:start -->"
END_MARKER = "<!-- governance:auto:end -->"

RULE_FILE_HEADER = """---
description: Core governance doctrine for all code changes
globs:
alwaysApply: true
---

# Governance Doctrine

These rules apply to every code change in this repository. The canonical
source is `config/governance-contract.yaml`; this file is auto-generated by
`scripts/generate-governance-surfaces.py`. Do not edit directly.
"""


def load_contract() -> dict:
    if not CONTRACT.exists():
        print(f"ERROR: {CONTRACT} not found", file=sys.stderr)
        sys.exit(1)
    return yaml.safe_load(CONTRACT.read_text(encoding="utf-8"))


def _bullets(items: list[str]) -> list[str]:
    return [f"- {item}" for item in items]


def _numbered(items: list[str]) -> list[str]:
    return [f"{i}. {item}" for i, item in enumerate(items, start=1)]


def render_block(c: dict) -> str:
    """Render the full governance markdown block, deterministically."""
    out: list[str] = []

    pillars = c.get("pillars", [])
    if pillars:
        out += ["## Core Doctrine Pillars", ""]
        for p in pillars:
            out += [f"{p['ordinal']}. **{p['title']}** — {p['rule']}", ""]

    behavior = c.get("agent_behavior", {})
    if behavior.get("rules"):
        out += [f"## {behavior.get('title', 'Agent Behavioral Contract')}", ""]
        out += _numbered(behavior["rules"]) + [""]

    workflow = c.get("agent_workflow", {})
    if workflow.get("rules"):
        out += [f"## {workflow.get('title', 'Agent Task & PR Workflow')}", ""]
        out += _bullets(workflow["rules"]) + [""]

    hygiene = c.get("repo_hygiene", {})
    if hygiene:
        out += ["## Repo Hygiene", ""]
        for pat in hygiene.get("forbidden_root_patterns", []):
            out.append(f"- FORBIDDEN at repo root: `{pat}`")
        if hygiene.get("report_location"):
            out.append(f"- Reports location: `{hygiene['report_location']}`")
        if hygiene.get("archive_location"):
            out.append(f"- Archive location: `{hygiene['archive_location']}`")
        out += _bullets(hygiene.get("naming_rules", []))
        out.append("")

    standards = c.get("code_standards", {})
    if standards:
        out += ["## Code Standards", ""]
        for lang, spec in standards.items():
            if not isinstance(spec, dict) or not spec.get("rules"):
                continue
            out += [f"### {lang.title()}", ""]
            out += _bullets(spec["rules"]) + [""]

    simple_sections = [
        ("module_boundaries", "Module Boundaries"),
        ("database", "Database Safety"),
        ("branch_hygiene", "Branch Hygiene"),
        ("testing", "Testing"),
        ("safety", "Safety"),
        ("external_integrations", "External Integrations"),
    ]
    for key, title in simple_sections:
        rules = c.get(key, {}).get("rules", [])
        if rules:
            out += [f"## {title}", ""]
            out += _bullets(rules) + [""]

    return "\n".join(out).rstrip() + "\n"


def spliced(text: str, block: str) -> str:
    """Insert/replace the governance block between markers in a marker file."""
    payload = f"{START_MARKER}\n\n{block}\n{END_MARKER}"
    if START_MARKER in text and END_MARKER in text:
        pre = text.split(START_MARKER)[0]
        post = text.split(END_MARKER, 1)[1]
        return pre + payload + post
    return text.rstrip() + "\n\n" + payload + "\n"


def expected_rule_file(block: str) -> str:
    return RULE_FILE_HEADER + "\n" + block


def main() -> int:
    check_mode = "--check" in sys.argv[1:]
    contract = load_contract()
    block = render_block(contract)
    surfaces = contract.get("surfaces", {})

    drifted: list[str] = []

    for rel in surfaces.get("marker_files", []):
        path = ROOT / rel
        if not path.exists():
            print(f"WARN: marker file missing, skipping: {rel}", file=sys.stderr)
            continue
        current = path.read_text(encoding="utf-8")
        expected = spliced(current, block)
        if current != expected:
            if check_mode:
                drifted.append(rel)
            else:
                path.write_text(expected, encoding="utf-8", newline="\n")
                print(f"updated {rel}")

    rule_rel = surfaces.get("rule_file")
    if rule_rel:
        path = ROOT / rule_rel
        expected = expected_rule_file(block)
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != expected:
            if check_mode:
                drifted.append(rule_rel)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8", newline="\n")
                print(f"updated {rule_rel}")

    if check_mode:
        if drifted:
            print(
                "GOVERNANCE DRIFT — surfaces do not match the contract:",
                file=sys.stderr,
            )
            for rel in drifted:
                print(f"  - {rel}", file=sys.stderr)
            print(
                "Fix: python scripts/generate-governance-surfaces.py", file=sys.stderr
            )
            return 1
        print("governance surfaces aligned with contract")
    return 0


if __name__ == "__main__":
    sys.exit(main())
