#!/usr/bin/env python3
"""Generate the metadata-only GitHub routing proposal workflow.

The workflow intentionally uses only GitHub event metadata and the pull-request
files API.  It never checks out or executes pull-request content.

Usage:
    python scripts/generate-routing-workflow.py
    python scripts/generate-routing-workflow.py --check
    python scripts/generate-routing-workflow.py --emit
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_PATH = ROOT / ".github" / "workflows" / "mc-routing-metadata.yml"
FORBIDDEN_PATTERNS = (
    "actions/checkout",
    "pull_request_target",
    "run:",
    "npm ",
    "pip ",
    "git checkout",
    "restore-cache",
)

WORKFLOW = r"""# Generated by scripts/generate-routing-workflow.py. DO NOT EDIT.
# Metadata-only routing proposal: no checkout or pull-request code execution.
name: MC Routing Metadata

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  propose-routing:
    name: Propose routing from pull request metadata
    runs-on: ubuntu-latest
    steps:
      - name: Send metadata-only routing proposal to Mission Control
        uses: actions/github-script@v7
        env:
          MC_BASE_URL: ${{ secrets.PLX_MC_BASE_URL }}
        with:
          github-token: ${{ github.token }}
          script: |
            const baseUrl = process.env.MC_BASE_URL?.replace(/\/$/, "");
            if (!baseUrl) {
              core.notice("PLX_MC_BASE_URL is not configured; routing proposal skipped.");
              return;
            }

            const pr = context.payload.pull_request;
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              per_page: 100,
            });
            const oidcToken = await core.getIDToken("plx-mc-routing-propose");
            const payload = {
              repository: `${context.repo.owner}/${context.repo.repo}`,
              repositoryId: context.payload.repository.id,
              eventName: context.eventName,
              action: context.payload.action,
              prNumber: pr.number,
              headSha: pr.head.sha,
              mergeSha: pr.merge_commit_sha || null,
              headRef: pr.head.ref,
              baseBranch: pr.base.ref,
              sourceBranch: pr.head.ref,
              title: pr.title,
              body: pr.body || "",
              labels: pr.labels.map((label) => label.name),
              changedPaths: files.map((file) => file.filename),
              author: pr.user.login,
              workflowRef: process.env.GITHUB_WORKFLOW_REF,
            };
            const response = await fetch(`${baseUrl}/api/routing/propose`, {
              method: "POST",
              headers: {
                authorization: `Bearer ${oidcToken}`,
                "content-type": "application/json",
              },
              body: JSON.stringify(payload),
            });
            const result = await response.json().catch(() => ({}));
            if (!response.ok) {
              core.setFailed(
                `MC routing proposal failed (${response.status}): ${JSON.stringify(result)}`
              );
              return;
            }
            core.notice(`MC routing proposal recorded: ${result.data?.proposalId ?? "unknown"}`);
"""


def validate_security_contract(workflow: str) -> None:
    """Reject workflow constructs that could execute pull-request content."""
    unsafe = [pattern for pattern in FORBIDDEN_PATTERNS if pattern in workflow.lower()]
    if unsafe:
        raise ValueError(
            "routing workflow is not metadata-only; forbidden patterns: "
            + ", ".join(unsafe)
        )


def main() -> int:
    expected = WORKFLOW
    try:
        validate_security_contract(expected)
    except ValueError as error:
        print(f"ROUTING WORKFLOW SECURITY CONTRACT FAILED — {error}", file=sys.stderr)
        return 1

    if "--emit" in sys.argv[1:]:
        sys.stdout.write(expected)
        return 0

    if "--check" in sys.argv[1:]:
        current = (
            CANONICAL_PATH.read_text(encoding="utf-8")
            if CANONICAL_PATH.exists()
            else ""
        )
        if current != expected:
            print(
                "ROUTING WORKFLOW DRIFT — .github/workflows/mc-routing-metadata.yml "
                "does not match the generator source.",
                file=sys.stderr,
            )
            print("Fix: python scripts/generate-routing-workflow.py", file=sys.stderr)
            return 1
        print("routing workflow aligned with generator source")
        return 0

    CANONICAL_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {CANONICAL_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
